### ISSUE TITLE
Feature: Add arguments to getPurchaseHistory() function

### ISSUE THREAD

**Issue by Jonakemon** [LauLamanApps/iZettleApi#26]
The API specifies the possibility to add arguments when requesting purchase history. This is currently not supported by this library. See [the docs](https://github.com/iZettle/api-documentation/blob/master/purchase.adoc#get-purchase-history) for more details.

Without specifying any arguments, the `getPurchaseHistory()` function will request the entire purchase history, resulting in a 500 error from iZettle.

**Comment by mattsims** [comment]
@LauLaman I see you self-assigned this a couple of weeks ago – does this mean you're working on it?  Let me know if not as I may be able to help out 👍

**Comment by LauLaman** [comment]
Hi @mattsims,

i've added this to my to-do list but did not found the time yet to get started on this. feel free to open a PR
