### ISSUE TITLE
Get one product result

### ISSUE THREAD

**Issue by Cannonb4ll** [LauLamanApps/iZettleApi#28]
Is it possible to get one result back from this package? I've seen the getProducts() method, but it would be nice if you could 'search' for a product since there's an endpoint for that too.

Something in the lines of;

```php
$productClient = IzettleClientFactory::getProductClient($izettleClient);

dd($productClient->getProduct('uuid'));
```

**Comment by LauLaman** [comment]
@Cannonb4ll i just created a PR for this (#31)

Will be released with the 1.0 version
🤗
